---
- hosts: qa
  tasks:
    - name: Kernel
      debug: msg="  {{ansible_kernel}}"

    - name: Hostname
      debug: msg="{{ansible_hostname}}"

    - name: Distribution
      debug: msg="{{ansible_distribution}}"

    - name: Kernel
      debug: var=ansible_architecture
      debug: var=inventory_name
      debug: var=groups
      debug: var=group_names
      debug: var=host_var
    

